#!/bin/bash

commontestdir=`echo "$(cd $(dirname $0); pwd)/../"`
#field=Array
#tocheck=hoistedsunk
message="There are 0 get/set pairs and 0 sets to sink out of the loop"
testtype=negative

if [ -f $commontestdir/postproc_common ]; then
    source $commontestdir/postproc_common
fi

